### ISSUE TITLE
make failed when connect the server

### ISSUE THREAD

**Issue by deathknight0718** [shadowsocks/shadowsocks-qt5#667] opened 2018-02-12 07:54 UTC
OS: fedora 26
kernel: 4.14.16-200
ss-qt5: 3.0.0-1
log text:
```
Process 2968 (ss-qt5) of user 1000 dumped core.

Stack trace of thread 2968:
#0  0x00007f9d8d1329fb raise (libc.so.6)
#1  0x00007f9d8d134800 abort (libc.so.6)
#2  0x00007f9d8d178bb1 __libc_message (libc.so.6)
#3  0x00007f9d8d181ea5 malloc_consolidate.part.1 (libc.so.6)
#4  0x00007f9d8d183ea6 _int_free (libc.so.6)
#5  0x00007f9d8d1893be __libc_free (libc.so.6)
#6  0x00007f9d8bf1c3ba _ZN5Botan17Pooling_Allocator7destroyEv (libbotan-1.10.so.1)
#7  0x00007f9d8c016152 _ZN5Botan13Library_StateD1Ev (libbotan-1.10.so.1)
#8  0x00007f9d8c014ba6 _ZN5Botan23Global_State_Management16set_global_stateEPNS_13Library_StateE (libbotan-1.10.so.1)
#9  0x00007f9d8c014e17 _ZN5Botan18LibraryInitializer10initializeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (libbotan-1.10.so.1)
#10 0x00007f9d8ebe4379 _ZN3QSS10ControllerC2ENS_7ProfileEbbP7QObject (libQtShadowsocks.so.2)
#11 0x0000564cd76471f1 _ZN10Connection5startEv (ss-qt5)
#12 0x0000564cd7638a20 _ZN10MainWindow9onConnectEv (ss-qt5)
#13 0x00007f9d8dfffe27 _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
#14 0x00007f9d8ef58542 _ZN7QAction9triggeredEb (libQt5Widgets.so.5)
#15 0x00007f9d8ef5ac5b _ZN7QAction8activateENS_11ActionEventE (libQt5Widgets.so.5)
#16 0x00007f9d8f0d73a4 _ZN12QMenuPrivate19activateCausedStackERK7QVectorI8QPointerI7QWidgetEEP7QActionNS7_11ActionEventEb (libQt5Widgets.so.5)
#17 0x00007f9d8f0de91b _ZN12QMenuPrivate14activateActionEP7QActionNS0_11ActionEventEb (libQt5Widgets.so.5)
#18 0x00007f9d8f0df7e3 _ZN5QMenu17mouseReleaseEventEP11QMouseEvent (libQt5Widgets.so.5)
#19 0x00007f9d8ef9d428 _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5)
#20 0x00007f9d8f0e1abb _ZN5QMenu5eventEP6QEvent (libQt5Widgets.so.5)
#21 0x00007f9d8ef5ec9c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
#22 0x00007f9d8ef66a3f _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
#23 0x00007f9d8dfd74a7 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
#24 0x00007f9d8ef65a12 _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Eb (libQt5Widgets.so.5)
#25 0x00007f9d8efb7f13 _ZN13QWidgetWindow16handleMouseEventEP11QMouseEvent (libQt5Widgets.so.5)
#26 0x00007f9d8efba87f _ZN13QWidgetWindow5eventEP6QEvent (libQt5Widgets.so.5)
#27 0x00007f9d8ef5ec9c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
#28 0x00007f9d8ef664e4 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
#29 0x00007f9d8dfd74a7 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
#30 0x00007f9d8e32db73 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE (libQt5Gui.so.5)
#31 0x00007f9d8e32f755 _ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE (libQt5Gui.so.5)
#32 0x00007f9d8e3095cb _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5)
#33 0x00007f9d7ec4f130 _ZL23userEventSourceDispatchP8_GSourcePFiPvES1_ (libQt5XcbQpa.so.5)
#34 0x00007f9d883c0257 g_main_context_dispatch (libglib-2.0.so.0)
#35 0x00007f9d883c05f8 g_main_context_iterate.isra.25 (libglib-2.0.so.0)
#36 0x00007f9d883c068c g_main_context_iteration (libglib-2.0.so.0)
#37 0x00007f9d8e02847f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#38 0x00007f9d8dfd622a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#39 0x00007f9d8dfde884 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
#40 0x0000564cd76366f8 main (ss-qt5)
#41 0x00007f9d8d11c88a __libc_start_main (libc.so.6)
#42 0x0000564cd7636cfa _start (ss-qt5)

Stack trace of thread 2972:
#0  0x00007f9d8d200a5d poll (libc.so.6)
#1  0x00007f9d883c0579 g_main_context_iterate.isra.25 (libglib-2.0.so.0)
#2  0x00007f9d883c068c g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f9d7202df3d dconf_gdbus_worker_thread (libdconfsettings.so)
#4  0x00007f9d883e7516 g_thread_proxy (libglib-2.0.so.0)
#5  0x00007f9d8cee436d start_thread (libpthread.so.0)
#6  0x00007f9d8d20cb4f __clone (libc.so.6)

Stack trace of thread 2971:
#0  0x00007f9d8d200a5d poll (libc.so.6)
#1  0x00007f9d87647c97 _xcb_conn_wait (libxcb.so.1)
#2  0x00007f9d87649a8a xcb_wait_for_event (libxcb.so.1)
#3  0x00007f9d7ebec379 _ZN15QXcbEventReader3runEv (libQt5XcbQpa.so.5)
#4  0x00007f9d8de2bc72 _ZN14QThreadPrivate5startEPv (libQt5Core.so.5)
#5  0x00007f9d8cee436d start_thread (libpthread.so.0)
#6  0x00007f9d8d20cb4f __clone (libc.so.6)

Stack trace of thread 2973:
#0  0x00007f9d8d200a5d poll (libc.so.6)
#1  0x00007f9d883c0579 g_main_context_iterate.isra.25 (libglib-2.0.so.0)
#2  0x00007f9d883c068c g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f9d883c06d1 glib_worker_main (libglib-2.0.so.0)
#4  0x00007f9d883e7516 g_thread_proxy (libglib-2.0.so.0)
#5  0x00007f9d8cee436d start_thread (libpthread.so.0)
#6  0x00007f9d8d20cb4f __clone (libc.so.6)

Stack trace of thread 2974:
#0  0x00007f9d8d200a5d poll (libc.so.6)
#1  0x00007f9d883c0579 g_main_context_iterate.isra.25 (libglib-2.0.so.0)
#2  0x00007f9d883c0912 g_main_loop_run (libglib-2.0.so.0)
#3  0x00007f9d78f40db6 gdbus_shared_thread_func (libgio-2.0.so.0)
#4  0x00007f9d883e7516 g_thread_proxy (libglib-2.0.so.0)
#5  0x00007f9d8cee436d start_thread (libpthread.so.0)
#6  0x00007f9d8d20cb4f __clone (libc.so.6)

Stack trace of thread 2975:
#0  0x00007f9d8d200a5d poll (libc.so.6)
#1  0x00007f9d883c0579 g_main_context_iterate.isra.25 (libglib-2.0.so.0)
#2  0x00007f9d883c068c g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f9d8e02847f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
#4  0x00007f9d8dfd622a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
#5  0x00007f9d8de2799a _ZN7QThread4execEv (libQt5Core.so.5)
#6  0x00007f9d8e70b689 _ZN22QDBusConnectionManager3runEv (libQt5DBus.so.5)
#7  0x00007f9d8de2bc72 _ZN14QThreadPrivate5startEPv (libQt5Core.so.5)
#8  0x00007f9d8cee436d start_thread (libpthread.so.0)
#9  0x00007f9d8d20cb4f __clone (libc.so.6)

Stack trace of thread 2977:
#0  0x00007f9d8ceea97b pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007f9d5858b14b util_queue_thread_func (nouveau_dri.so)
#2  0x00007f9d5858b067 impl_thrd_routine (nouveau_dri.so)
#3  0x00007f9d8cee436d start_thread (libpthread.so.0)
#4  0x00007f9d8d20cb4f __clone (libc.so.6)
```

**Comment by librehat** [comment] 2018-02-14 12:43
what is the version of `libQtShadowsocks` package?

**Comment by deathknight0718** [comment] 2018-03-06 03:27
libQtShadowsocks.x86_64  version : 2.0.2-1.fc26

**Comment by librehat** [comment] 2018-04-08 21:08
Do you remember what you did to trigger this? I can't reproduce it on Fedora 27

**Comment by librehat** [comment] 2018-05-21 20:45
Try latest version and it should be fixed

**Closed** 2018-05-21 20:44 UTC

**Comment by deathknight0718** [comment] 2018-06-10 10:04
Yes,its work well,thanks.
