### ISSUE TITLE
Ubuntu 18.04LTS chacha20加密方式的线路一连接就退出

### ISSUE THREAD

**Issue by PiterFan** [shadowsocks/shadowsocks-qt5#633] opened 2017-12-20 06:26 UTC
Ubuntu 18.04LTS chacha20加密方式的线路一连接就退出，终端显示如下信息：
```
Initialising cipher: chacha20
Running in local mode.
SOCKS5 port is 43583
Running as a HTTP proxy server
TCP server listening at 127.0.0.1:1080
terminate called after throwing an instance of 'std::length_error'
  what():  The IV length for ChaCha20 is invalid
```

**Comment by x1596357** [comment] 2017-12-24 09:11
使用appimage的新版

**Comment by librehat** [comment] 2018-01-05 22:44
It should have been fixed in latest release

**Comment by ldsink** [comment] 2018-01-12 10:22
```shell
➜  ~ ss-qt5 
Initialising cipher: chacha20
Running in local mode.
Listen UDP socket state changed to QAbstractSocket::BoundState
TCP server listening at 127.0.0.1:1080
terminate called after throwing an instance of 'std::length_error'
  what():  The IV length for ChaCha20 is invalid
[1]    19085 abort      ss-qt5
➜  ~ ss-qt5 --version
shadowsocks-qt5 3.0.0
```
 Deepin 15.5 unstable（Base on Debian 8.0） still has problem.

**Comment by ldsink** [comment] 2018-01-12 10:25
Please reopen this issue, thanks very much.

**Comment by librehat** [comment] 2018-01-12 13:18
@ldsink are you using the latest version 3.0?

**Comment by librehat** [comment] 2018-01-12 13:18
Reopen

**Comment by liuwenhuan** [comment] 2018-01-13 10:27
same issue as ldsink , use deepin 15.5。

**Comment by ldsink** [comment] 2018-01-15 02:32
AppImage running without problems， but ss-qt5(3.0.0) install from repository has the error.

I replaced  /usr/bin/ss-qt5 with AppImage(rename to ss-qt5) and solve the error now.

This problem is caused by different compiler environment?

**Comment by librehat** [comment] 2018-01-15 21:27
AppImage uses botan-2. In Botan-1, the custom Chacha implementation is used

**Comment by librehat** [comment] 2018-01-16 19:31
However, this should have been fixed in https://github.com/shadowsocks/libQtShadowsocks/pull/152
Can you check what version of `libqtshadowsocks` you have? @ldsink

**Comment by librehat** [comment] 2018-01-16 19:32
You probably can do `shadowsocks-libqss -v`

**Comment by ldsink** [comment] 2018-01-17 02:40
`sudo apt list | grep libqt`
Result:
```
libqtshadowsocks/panda,now 2.0.0-1 amd64 [installed,automatic]
libqtshadowsocks-dbgsym/panda 2.0.0-1 amd64
libqtshadowsocks-dev/panda 2.0.0-1 amd64
```

**Comment by librehat** [comment] 2018-01-17 11:45
I suspect it is an old build of `libQtShadowsocks` that didn't have the fix. `2.0.1` doesn't have this problem in my local PC

**Comment by librehat** [comment] 2018-01-17 15:27
As above. Please update the library. This should have already been fixed.

**Closed by librehat** 2018-01-17 15:27 UTC
Labels: need more info
